export const UnitCode = {
	PIECE: "H87",
	ONE: "C62",
	KILOGRAM: "KGM",
	GRAM: "GRM",
	TONNE: "TNE",
	METRE: "MTR",
	CENTIMETRE: "CMT",
	MILLIMETRE: "MMT",
	KILOMETRE: "KMT",
	SQUARE_METRE: "MTK",
	SQUARE_CENTIMETRE: "CMK",
	CUBIC_METRE: "MTQ",
	CUBIC_CENTIMETRE: "CMQ",
	LITRE: "LTR",
	MILLILITRE: "MLT",
	KILOWATT_HOUR: "KWH",
	MEGAWATT_HOUR: "MWH",
	DAY: "DAY",
	HOUR: "HUR",
	MINUTE: "MIN",
	WEEK: "WEE",
	MONTH: "MON",
	YEAR: "ANN",
	SET: "SET",
	PAIR: "PR",
	PACK: "XPK",
	PALLET: "XPX",
	BOTTLE: "XBO",
	BOX: "XBX",
	CARTON: "XCT",
	CASE: "XCS",
	CRATE: "XCR",
	DRUM: "XDR",
	BARREL_CASK: "XBC",
	FLAT_RATE: "LS",
	PERCENT: "P1",
	KILOWATT: "KWT",
	MEGAWATT: "MAW",
} as const;

export type UnitCode = (typeof UnitCode)[keyof typeof UnitCode];
export const VALID_UNIT_CODES: Set<string> = new Set(Object.values(UnitCode));
